[package]
name = "inspect_wav"
version = "0.1.0"
edition = "2021"

[dependencies]
binrw = "0.13.3"
byteorder = "1.5.0"
clap = { version = "4.5.3", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.27.0"
lazy_static = "1.4.0"
owo-colors = "4.0.0"
ratatui = "0.26.1"
serde_json = "1.0.114"
